### PR TITLE
Fix for build with PlatformIO

### PR DESCRIPTION
**Pull request by LieBtrau**
Signed-off-by: Christoph Tack <prog.send@gmail.com>

### CODE REVIEW

**Review by rkinnett — CHANGES_REQUESTED** [review]
Thanks or the PR!  These are all good corrections, although lines 44 and 45 should remain commented per the preceding explanation.  If you could please revert those lines then I'll pull this in.  Much appreciated!

Also, I would love to hear about it if you made use of this project.  Cheers

**Comment by LieBtrau** [comment]
Hi Ryan,
The two lines are commented again as you requested.  
I discovered your project while working on [a digital walkie talkie](https://hackaday.io/project/174231-digital-walkie-talkie).  It's been a while since I last worked on it.  Family and other projects took priority.  You may know it all too well.

**Review by rkinnett — APPROVED** [review]

**Comment by rkinnett** [comment]
That looks like an awesome project!

Another question about this pull request.  As best I can tell, "AsyncUDP.h" with UDP in all caps is the default library for wifi-enabled arduino boards with the arduino compiler.  I don't see an espressif-unique implementation of AsyncUDP.h in their github repo.  Where did you get "AsyncU**dp**.h"?  I can't even find mention of that capitalization in google.  Is there a platformio-specific arduino stack?

**Comment by rkinnett** [comment]
Are you spinning your digital walkie talkie project back up, or exploring something new?  Was this vban-based project useful for troubleshooting or as code reference?  If I was to start my esp32 tnc project from scratch I would probably not use vban, but rather find some other well-supported protocol or make my own python or java-based transceiver app and just use plain UDP packets with self-defined protocol.  Anyways, I am following your hackaday project and am interested in collaborating if you're interested.

**Comment by LieBtrau** [comment]
Hi Ryan,
Are you confusing WiFiUdp.h with AsyncUDP.h, because that's the line I changed.   WiFiUdp.h exists in this "camel-case" format.  Google will tell you that ;-).
The digital-walkie talkie project is a shelved for the moment.  I don't have a real purpose for it, so there's no real incentive to continue working on it.  For the moment it's all loose bits and pieces.  There's no high-level protocol yet.  I also like to use something standard, but I can't find any suitable protocol that has a low overhead.  Maybe google-protocolbuffers can be used.  I don't have experience with these yet, but it should be fairly simple to port the custom code to different platforms and programming languages.
I might help you in your project if you think that could be more useful.
If you're unhappy with VBAN, then what's holding you back to throw it out and try something different?  It's not always the fastest route that brings you to the destination.  Sometimes the scenic route is more desirable.

**Comment by rkinnett** [comment]
I see, right, I mixed up WifiUdp with another thing I happened to be looking into for another project.

My esp32 radio interface project is also shelved.  This 2-way relay project was one of many stepping stones for that project.

Regarding VBAN, thinking about it a bit more, I probably wouldn't throw that out unless I got far enough along to make a packaged product, in which case I would write my own app to go with it.  VBAN integrates with PC audio better than anything I could put together in short time, and it worked well with the radio communication software I was using.  It took some work to shoehorn VBAN to work with the ESP32, but it was worthwhile.  I guess I mentioned it in case you were considering using VBAN for your project.  Since you have design freedom on both ends of your esp32-esp32 link, you could use plain UDP and make up your own packet format.

Thanks for the PR!  I hope it helps folks using platformio.

**Pull request merged**
